/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 5fe7111d67da9d382b949fbb4486ea69)
interface __BaseEnv_Env {
	KEYBOX_DB: D1Database;
	DEVICE_CATALOG_DB: D1Database;
	OBSERVATION_QUEUE: Queue;
	VERDICT_KEY_ID: string;
	RULESET_VERSION: string;
	ALLOWED_PACKAGE: string;
	CATALOG_VERSION: string;
	OBSERVATION_MIN_SOURCES: string;
	OBSERVATION_MIN_NETWORKS: string;
	OBSERVATION_RETENTION_DAYS: string;
	VERDICT_PRIVATE_KEY: string;
	OBSERVATION_NETWORK_KEY: string;
	TRUSTED_SIGNER_DIGESTS: string;
	CHALLENGES: DurableObjectNamespace<import("./src/index").ChallengeStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChallengeStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VERDICT_KEY_ID" | "RULESET_VERSION" | "ALLOWED_PACKAGE" | "CATALOG_VERSION" | "OBSERVATION_MIN_SOURCES" | "OBSERVATION_MIN_NETWORKS" | "OBSERVATION_RETENTION_DAYS" | "VERDICT_PRIVATE_KEY" | "OBSERVATION_NETWORK_KEY" | "TRUSTED_SIGNER_DIGESTS">> {}
}
